kind: Namespace
apiVersion: v1
metadata:
  name: front
  labels:
    name: front
    app: front
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: front
  labels:
    app: front
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: front
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: front
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: helloworld
          image:  mnnsashraf/helloworld-nodejs:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
