apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    kind : "worker"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    kind : "worker"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    kind : "worker"
spec:
  replicas: 2
  selector:
    matchLabels:
      kind : "worker"
  template:
    metadata:
      labels:
         kind : "worker"
    spec:
      containers:
      - name: helloworld
        image: nginx:stable
        ports:
        - containerPort: 80